name: Create Release Archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'pcd-io.zip'
        exclusions: '*.git* *.pyc README.md *media*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "pcd-io.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
